### ISSUE TITLE
Doesn't work for guilds without an image

### ISSUE THREAD

**Issue by SamboyCoding** [NurMarvin/guild-profile#1]
As in title, the option to view the profile doesn't work for Guilds without a server image set (so those using the default "initials" icon)

Video of the issue: https://streamable.com/o3jwau 

```ini
# Debugging Information | Result created: Today at 19:44

[SYSTEM / DISCORD]
Locale="en-GB"
OS="Windows 10 64-bit"
Architecture="x64"
ReleaseChannel="canary"
AppVersion="0.0.266"
BuildNumber="64065"
BuildID="6a76559"
Experiments="3/42"

[GIT]
Upstream="Official"
Revision="[179a5e1]"
Branch="v2-dev"
Latest="true"
```

**Comment by NurMarvin** [comment]
hm interesting, will have to see what's causing that issue and will try to fix it ASAP
