### ISSUE TITLE
Add Icon in Guild Header

### ISSUE THREAD

**Issue by botatooo** [NurMarvin/guild-profile#12]
Compared to all of the other guild header popup things, "Server Profile" does not have an icon, see following;
![image](https://i.imgur.com/NJUXwEg.png)

If this possibly could be added, thanks.

**Comment by NurMarvin** [comment]
I'll cook something up

**Comment by fuwwy** [comment]
The news icon from the features list would look nice imo

**Comment by NurMarvin** [comment]
I've added an icon in https://github.com/NurMarvin/guild-profile/commit/d7469defc16416744944d0604259a8d37db36805 which you can see below which is a slightly modified version of the rich presence icon.<

![image](https://user-images.githubusercontent.com/17235016/93129425-42f26100-f6d1-11ea-85cd-1c27efaf8ba9.png)
