### ISSUE TITLE
Broken with the new Discord update

### ISSUE THREAD

**Issue by iblowmymind** [NurMarvin/guild-profile#31]
Discord decided to rename, like, 90% of its CSS classes, so the theme doesn't work at the moment.

**Comment by iblowmymind** [comment]
It seems to have fixed itself.

**Comment by DracoClaw** [comment]
Yeah I don't think it "fixed itself"

![image](https://user-images.githubusercontent.com/34274162/148703365-2d275254-66b3-4d87-90d8-17c96382bbc1.png)
