### ISSUE TITLE
[UI Bug?] weird popup output

### ISSUE THREAD

**Issue by owocado** [NurMarvin/guild-profile#38]
on recent canary versions, the guild profile popup output weirdly.

![image](https://user-images.githubusercontent.com/24418520/178136170-926eb4ed-f0f3-4543-b36e-0855dfe2549d.png)

If the cause of this is not caused by the plugin then please close the issue. Not sure myself.

**Comment by NurMarvin** [comment]
It's because the webpack module containing the used CSS classes is lazy loaded. If you load the user profile modal (the modal this one is based on) first, the CSS classes will be loaded, however I'm not aware of any efficient way to load the webpack modules programatically.
