### ISSUE TITLE
Server Profile Button Locked

### ISSUE THREAD

**Issue by DracoClaw** [NurMarvin/guild-profile#9]
The 'Server Profile' button is selected by default when opening the server R-Click menu. Even when not hovering the option it is selected.

**Comment by DracoClaw** [comment]
This is still an issue

**Comment by NurMarvin** [comment]
I'll have a look tomorrow.

**Comment by fuwwy** [comment]
@DracoClaw Are you sure you have the latest version of the plugin? The changes I did on #10 fixed it for me.

**Comment by DracoClaw** [comment]
I'll redownload the plugin, but Powercord auto updates so I believe I am. But lemme try a fresh version.

**Comment by DracoClaw** [comment]
Yeah, with a fresh install its still happening.
![13-09-20-314](https://user-images.githubusercontent.com/34274162/93006169-bc6b4180-f561-11ea-9e34-4916d4ee47bb.gif)

**Comment by DracoClaw** [comment]
Fixed! Thank you so much! <3
